export const PLAYLIST = [
  {
    id: 1,
    title: 'American Idiot',
    artist: 'Green Day',
    duration: '2:54',
    src: '/audio/American Idiot.mp3',
    cover: '/images/green day.jpg',
  },
  {
    id: 2,
    title: 'Carry On Wayward Son',
    artist: 'Kansas',
    duration: '5:26',
    src: '/audio/Carry On Wayward Son.mp3',
    cover: '/images/kansas.jpg',
  },
  {
    id: 3,
    title: 'Gone Away',
    artist: 'The Offspring',
    duration: '4:29',
    src: '/audio/Gone Away.mp3',
    cover: '/images/offspring.jpg',
  },
  {
    id: 4,
    title: 'Highway To Hell',
    artist: 'AC/DC',
    duration: '3:28',
    src: '/audio/Highway To Hell.mp3',
    cover: '/images/acdc.jpg',
  },
  {
    id: 5,
    title: 'St. Anger',
    artist: 'Metallica',
    duration: '7:21',
    src: '/audio/St. Anger.mp3',
    cover: '/images/metallica.jpg',
  },
];
